version: '3.8'

volumes:
  postgres_data: {}

services:
  backend:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - .:/backend
    command:
      python manage.py runserver 0.0.0.0:8000
    env_file: ../.env

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ../.env
